# Generated by Django 3.2 on 2022-12-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221201_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('Tipo', models.IntegerField(choices=[(1, 'Anular cita'), (2, 'Cambio de mi perfil'), (3, 'Otros')])),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
