# Generated by Django 3.2 on 2022-12-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_alter_event_id'),
        ('account', '0004_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='catalogue.event'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='Descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
