# Generated by Django 3.2 on 2022-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_deliveryoptions_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('MAIL', 'Te enviamos la confirmación por correo'), ('REGISTER YOUR DATA', 'Registra algunos datos junto a tu correo para mantenerte informado'), ('SMS', 'Te enviamos un SMS con la confirmación')], help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
