# Generated by Django 3.2 on 2022-11-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medics', to='catalogue.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(verbose_name='Date and time of appointment')),
                ('client_name', models.CharField(max_length=255)),
                ('client_surname', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='catalogue.medic')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
