# Generated by Django 3.2 on 2022-12-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_appointment_department_medic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='level',
        ),
        migrations.RemoveField(
            model_name='department',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='department',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='department',
            name='tree_id',
        ),
    ]
