# Generated by Django 3.2 on 2022-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20221201_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='slug',
            field=models.SlugField(default='ds8dasidhaiodhu12', max_length=255),
            preserve_default=False,
        ),
    ]
