# Generated by Django 3.2 on 2022-12-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_medic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
