# Generated by Django 3.2 on 2022-12-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_medic_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='slug',
        ),
    ]
