# Generated by Django 3.2 on 2022-12-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_remove_medic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
