# Generated by Django 3.2 on 2022-12-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_medic_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
