# Generated by Django 3.2 on 2022-12-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_event'),
        ('catalogue', '0010_medic_slug'),
    ]

    operations = [
    ]
