# Generated by Django 3.2 on 2022-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_merge_0002_event_0010_medic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='Departamento',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='Medico',
            field=models.CharField(default='Juan', max_length=200),
            preserve_default=False,
        ),
    ]
