# Generated by Django 3.2 on 2022-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_event_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='customer',
        ),
        migrations.AddField(
            model_name='event',
            name='client_email',
            field=models.EmailField(default='hola@gmail.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
