# Generated by Django 3.2 on 2022-12-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20221201_1947'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(verbose_name='Date and time of appointment')),
                ('client_name', models.CharField(max_length=255)),
                ('client_surname', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='catalogue.medic')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='medic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalogue.medic'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.appointment'),
            preserve_default=False,
        ),
    ]
